version: "3.8"
services:
  post_gre_sql:
    build: postgresql
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=asdqwe123
  fast_api_menu:
    build: ./
    ports: 
      - '8000:8000'
    stdin_open: true
    tty : true
    volumes:
      - ./:/app